"""Shared stop codes and path guards for BoundLore backup tooling."""
from __future__ import annotations

from pathlib import Path

STOP_WRONG_PROJECT = "STOP_WRONG_PROJECT"
STOP_STAGING_TARGET = "STOP_STAGING_TARGET"
STOP_OUTPUT_INSIDE_REPOSITORY = "STOP_OUTPUT_INSIDE_REPOSITORY"
STOP_CREDENTIALS_MISSING = "STOP_CREDENTIALS_MISSING"
STOP_ENCRYPTION_UNAVAILABLE = "STOP_ENCRYPTION_UNAVAILABLE"
STOP_ENCRYPTION_FAILED = "STOP_ENCRYPTION_FAILED"
STOP_CHECKSUM_FAILED = "STOP_CHECKSUM_FAILED"
STOP_MANIFEST_INCOMPLETE = "STOP_MANIFEST_INCOMPLETE"
STOP_STORAGE_INVENTORY_MISMATCH = "STOP_STORAGE_INVENTORY_MISMATCH"
STOP_EXTERNAL_UPLOAD_NOT_AUTHORIZED = "STOP_EXTERNAL_UPLOAD_NOT_AUTHORIZED"
STOP_NETWORK_FORBIDDEN = "STOP_NETWORK_FORBIDDEN"
STOP_CLEANUP_FAILED = "STOP_CLEANUP_FAILED"
STOP_UNKNOWN_BUCKET = "STOP_UNKNOWN_BUCKET"
STOP_UNSAFE_DEFAULT = "STOP_UNSAFE_DEFAULT"

# P5-E.10B-W5-P1 production snapshot preflight stop codes
STOP_PRODUCTION_SNAPSHOT_NOT_AUTHORIZED = "STOP_PRODUCTION_SNAPSHOT_NOT_AUTHORIZED"
STOP_PROJECT_IDENTITY_UNVERIFIED = "STOP_PROJECT_IDENTITY_UNVERIFIED"
STOP_RELEASE_GATE_NOT_LOCKED = "STOP_RELEASE_GATE_NOT_LOCKED"
STOP_PRODUCTION_DB_CONNECTION_FAILED = "STOP_PRODUCTION_DB_CONNECTION_FAILED"
STOP_RELEASE_GATE_QUERY_FAILED = "STOP_RELEASE_GATE_QUERY_FAILED"
STOP_UNKNOWN_DATABASE_SCHEMA = "STOP_UNKNOWN_DATABASE_SCHEMA"
STOP_UNKNOWN_STORAGE_BUCKET = "STOP_UNKNOWN_STORAGE_BUCKET"
STOP_OUTPUT_PATH_UNSAFE = "STOP_OUTPUT_PATH_UNSAFE"
STOP_FREE_SPACE_INSUFFICIENT = "STOP_FREE_SPACE_INSUFFICIENT"
STOP_DATABASE_CREDENTIAL_MISSING = "STOP_DATABASE_CREDENTIAL_MISSING"
STOP_STORAGE_CREDENTIAL_MISSING = "STOP_STORAGE_CREDENTIAL_MISSING"
STOP_WASABI_CREDENTIAL_MISSING = "STOP_WASABI_CREDENTIAL_MISSING"
STOP_PRODUCTION_KEY_RECIPIENT_MISSING = "STOP_PRODUCTION_KEY_RECIPIENT_MISSING"
STOP_PLAINTEXT_UPLOAD_ATTEMPTED = "STOP_PLAINTEXT_UPLOAD_ATTEMPTED"
STOP_DATABASE_DUMP_INCOMPLETE = "STOP_DATABASE_DUMP_INCOMPLETE"
STOP_STORAGE_EXPORT_INCOMPLETE = "STOP_STORAGE_EXPORT_INCOMPLETE"
STOP_INVENTORY_CHANGED_DURING_EXPORT = "STOP_INVENTORY_CHANGED_DURING_EXPORT"
STOP_EXTERNAL_TARGET_MISMATCH = "STOP_EXTERNAL_TARGET_MISMATCH"
STOP_REMOTE_SCOPE_NOT_AUTHORIZED = "STOP_REMOTE_SCOPE_NOT_AUTHORIZED"
STOP_REMOTE_UPLOAD_NOT_AUTHORIZED = "STOP_REMOTE_UPLOAD_NOT_AUTHORIZED"
STOP_CREDENTIAL_PERSISTENCE_RISK = "STOP_CREDENTIAL_PERSISTENCE_RISK"
STOP_LOCAL_CLEANUP_FAILED = "STOP_LOCAL_CLEANUP_FAILED"
STOP_VERACRYPT_WORKSPACE_NOT_MOUNTED = "STOP_VERACRYPT_WORKSPACE_NOT_MOUNTED"
STOP_PLAINTEXT_WORKSPACE_UNSAFE = "STOP_PLAINTEXT_WORKSPACE_UNSAFE"
STOP_PRODUCTION_KEY_RECIPIENT_INVALID = "STOP_PRODUCTION_KEY_RECIPIENT_INVALID"
STOP_GETOBJECT_NOT_AUTHORIZED = "STOP_GETOBJECT_NOT_AUTHORIZED"
STOP_LIVE_NETWORK_RESERVED = "STOP_LIVE_NETWORK_RESERVED"
STOP_LOCAL_ENCRYPTED_COPY_FAILED = "STOP_LOCAL_ENCRYPTED_COPY_FAILED"
STOP_UPLOAD_COUNT_NOT_PROVEN = "STOP_UPLOAD_COUNT_NOT_PROVEN"
FAIL_ROLE_PASSWORD_DATA_PRESENT = "FAIL_ROLE_PASSWORD_DATA_PRESENT"
FAIL_PRIVATE_KEY_PRESENT_IN_PUBLIC_RECIPIENT_FILE = "FAIL_PRIVATE_KEY_PRESENT_IN_PUBLIC_RECIPIENT_FILE"

# Known refs for guard messaging only — never used as live defaults.
KNOWN_PRODUCTION_REF = "ohkoojpzmptdfyowdgog"
KNOWN_STAGING_REF = "jzzgoiwfbuwiiyvwgwri"

BUCKET_ALLOWLIST = ("avatars", "discovery-uploads", "report-screenshots")

# Non-system schemas expected for later read-only discovery; unknown others stop.
SCHEMA_ALLOWLIST = (
    "public",
    "auth",
    "storage",
    "extensions",
    "graphql_public",
    "realtime",
    "graphql",
    "supabase_migrations",
    "vault",
)

MANIFEST_REQUIRED_KEYS = (
    "format_version",
    "backup_id",
    "created_at_utc",
    "source_type",
    "database_components",
    "storage_components",
    "file_count",
    "encrypted_size",
    "checksum_algorithm",
    "encryption_method",
    "tool_versions",
    "release_gate_expected_locked",
    "validation_status",
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def assert_output_outside_repo(output_dir: Path) -> None:
    root = repo_root().resolve()
    out = output_dir.resolve()
    try:
        out.relative_to(root)
    except ValueError:
        return
    raise SystemExit(f"{STOP_OUTPUT_INSIDE_REPOSITORY}: output must be outside repository ({out})")


def assert_project_ref(project_ref: str | None, *, allow_production_read: bool) -> None:
    if not project_ref:
        if allow_production_read:
            raise SystemExit(f"{STOP_WRONG_PROJECT}: project ref required")
        return
    if project_ref == KNOWN_STAGING_REF:
        raise SystemExit(f"{STOP_STAGING_TARGET}: staging ref is forbidden")
    if allow_production_read and project_ref != KNOWN_PRODUCTION_REF:
        raise SystemExit(f"{STOP_WRONG_PROJECT}: unexpected project ref")
    if (not allow_production_read) and project_ref == KNOWN_PRODUCTION_REF:
        raise SystemExit(
            f"{STOP_WRONG_PROJECT}: production ref supplied without -AllowProductionRead"
        )


def assert_no_network(no_network: bool, attempting_external: bool) -> None:
    if no_network and attempting_external:
        raise SystemExit(f"{STOP_NETWORK_FORBIDDEN}: external network blocked")
